version: '3.9'

services:
  api:
    build: .
    container_name: golootlo-backend
    ports:
      - '${PORT:-4000}:4000'
    environment:
      NODE_ENV: development
      PORT: 4000
      LOG_LEVEL: info
      API_PREFIX: /api/v1
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

